server:
  servlet:
    context-path: /docgen

  port: 8088

app:
  name: ${project.name}
  version: ${project.version}

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB